steps:
  # 第一步：自動將程式碼打包成容器映像檔
  - name: 'gcr.io/k8s-skaffold/pack'
    entrypoint: 'pack'
    # 👇 加入 env 區塊，強制要求 Google Buildpacks 在安裝套件前先升級 pip 且不從原始碼編譯
    env:
      - 'GOOGLE_PYTHON_PIP_VERSION=latest'
    args:
      - 'build'
      - 'gcr.io/$PROJECT_ID/deliveryorder'
      - '--builder=gcr.io/buildpacks/builder:v1'

  # 第二步：部署到 Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'deliveryorder'
      - '--image'
      - 'gcr.io/$PROJECT_ID/deliveryorder'
      - '--region'
      - 'asia-east1'

options:
  logging: CLOUD_LOGGING_ONLY
